
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      
  auth:
    build: ./auth
    ports:
      - "50051:50051"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=comics
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d comics"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pg.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5055:80"
    depends_on:
      db:
        condition: service_healthy
  
  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/migrations/:/migrations
    command: ["-path", "/migrations/", "-database", "postgres://admin:admin@db:5432/comics?sslmode=disable", "up"]

  email-service:
    build: ./email-service
    ports:
      - "8082:8082"
    env_file:
      - ./email-service/.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/metrics" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      email-service:
        condition: service_healthy

  grafana:
      image: grafana/grafana:latest
      ports:
        - "3001:3000"
      env_file:
        - ./email-service/.env
      depends_on:
        - prometheus